name: Check Bindgen Output

on:
  workflow_call:

jobs:
  check-bindgen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up stable Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Generate bindings
        run: cargo xtask generate-bindings

      - name: Check if the bindgen output changed
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "^lib/include/api.h$"; then
            git diff --exit-code
          fi
